version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Buzzing3Fridge
      - POSTGRES_DB=cookbook_development
    ports:
      - "5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundler exec rails server -e docker -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/cookbook
    ports:
      - "3000:3000"
    depends_on:
      - db
