default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres 
  password: Buzzing3Fridge
  pool: 5

development:
  <<: *default
  database: cookbook_development
  host: db


test:
  <<: *default
  database: cookbook_test
  host: localhost

